name: Deploy to Server

on:
  push:
    branches:
      - V3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/chat-messagebot
            git pull origin V3
            # If you use a virtual environment
            source venv/bin/activate
            # Restart your app, e.g. if using systemd:
            sudo systemctl restart chat-messagebot.service
